#!/bin/sh
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf 0

mkdir 0
cp -rf 0.org/* 0

# create geometry
runApplication blockMesh

paraFoam -touch

application=`getApplication`
runApplication $application
